# Generated by Django 3.2.7 on 2021-09-17 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lmaoRater', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blackcard',
            old_name='bCardNo',
            new_name='CardNo',
        ),
        migrations.RenameField(
            model_name='blackcard',
            old_name='wCardText',
            new_name='CardText',
        ),
        migrations.RenameField(
            model_name='score',
            old_name='bCardNo',
            new_name='BlackCard',
        ),
        migrations.RenameField(
            model_name='score',
            old_name='wCardNo',
            new_name='WhiteCard',
        ),
        migrations.RenameField(
            model_name='whitecard',
            old_name='wCardNo',
            new_name='CardNo',
        ),
        migrations.RenameField(
            model_name='whitecard',
            old_name='wCardText',
            new_name='CardText',
        ),
    ]
